---
sudo: required

env:
  - distribution: centos
    version: 7
  - distribution: debian
    version: jessie
  - distribution: debian
    version: stretch
  - distribution: ubuntu
    version: trusty
  - distribution: ubuntu
    version: xenial

services:
  - docker

before_install:
  - docker pull ${distribution}:${version}
  - docker build -f tests/Dockerfile.${distribution}-${version} -t ${distribution}-${version}:ansible .

script:
  - ./tests/run_test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
