---
sudo: required

language: python
python: "2.7"

services:
  - docker

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.2
  - ANSIBLE_VERSION=2.4.1
  - ANSIBLE_VERSION=2.4.0

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

script:
  - ansible-playbook -v -i tests/inventory --syntax-check tests/test.yml

jobs:
  include:
    - &test-playbook-stage
      stage: Test playbook on some scenarios
      env: distribution=centos version=7
      install:
        - docker pull ${distribution}:${version}
        - docker build -f tests/Dockerfile.${distribution}-${version} -t ${distribution}-${version}:ansible .
      script: ./tests/run_test
    - <<: *test-playbook-stage
      env: distribution=debian version=jessie
    - <<: *test-playbook-stage
      env: distribution=debian version=stretch
    - <<: *test-playbook-stage
      env: distribution=ubuntu version=trusty
    - <<: *test-playbook-stage
      env: distribution=ubuntu version=xenial

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
